-- =============================================================================
-- GEO-AWARE RMS: MASTER PRODUCTION SCHEMA (v5.0)
-- Combines Robust Data Logic with Supabase Auth
-- =============================================================================

-- 1. CLEANUP (Reset Script)

-- 2. ENUMS (Strict Data Types)
CREATE TYPE user_role AS ENUM ('super_admin', 'branch_manager');

CREATE TYPE order_status AS ENUM ('pending', 'accepted', 'in_kitchen', 'out_for_delivery', 'done', 'cancelled');

CREATE TYPE payment_method AS ENUM ('cash', 'credit_card', 'wallet');

CREATE TYPE payment_status AS ENUM ('pending', 'paid', 'failed', 'refunded');

-- 3. BRANCHES
-- Physical locations.
CREATE TABLE public.branches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    phone_contact TEXT,

-- Geospatial Data (The Polygon Definitions)
zones JSONB NOT NULL DEFAULT '[]',

-- Operational Status


is_active BOOLEAN DEFAULT TRUE,
    opening_time TIME,
    closing_time TIME,
    
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 4. PROFILES (Replaces system_users)
-- Links Supabase Auth (UUID) to our System Roles
CREATE TABLE public.profiles (
    id UUID REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
    username TEXT UNIQUE,
    full_name TEXT,
    role user_role DEFAULT 'branch_manager',

-- Security: Link this staff member to a specific branch


branch_id BIGINT REFERENCES public.branches(id) ON DELETE SET NULL,
    
    is_active BOOLEAN DEFAULT TRUE,
    last_login_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 5. CUSTOMERS
-- End-users (Whatsapp Users)
CREATE TABLE public.customers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    phone_number TEXT NOT NULL UNIQUE,
    full_name TEXT,
    language_pref TEXT DEFAULT 'ar',
    is_blocked BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone ('utc'::text, now())
);

-- 6. CUSTOMER ADDRESSES
-- Multiple addresses per customer
CREATE TABLE public.customer_addresses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT REFERENCES public.customers (id) ON DELETE CASCADE,
    address_text TEXT NOT NULL,
    latitude FLOAT NOT NULL,
    longitude FLOAT NOT NULL,
    label TEXT, -- e.g., "Home", "Work"
    is_default BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone ('utc'::text, now())
);

-- 7. ORDERS (The Robust Transaction Table)
CREATE TABLE public.orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    daily_seq INTEGER, -- Human readable #1, #2 (Resets Daily)

-- Relationships
branch_id BIGINT REFERENCES public.branches (id),
customer_id BIGINT REFERENCES public.customers (id),
address_id BIGINT REFERENCES public.customer_addresses (id),

-- Order Content
items JSONB NOT NULL, kitchen_notes TEXT,

-- Financials
subtotal DECIMAL(10, 2) DEFAULT 0.00,
delivery_fee DECIMAL(10, 2) DEFAULT 0.00,
tax DECIMAL(10, 2) DEFAULT 0.00,
discount DECIMAL(10, 2) DEFAULT 0.00,
total_price DECIMAL(10, 2) GENERATED ALWAYS AS (
    subtotal + delivery_fee + tax - discount
) STORED,

-- Payment Info
payment_method payment_method DEFAULT 'cash',
payment_status payment_status DEFAULT 'pending',

-- Status Flow
status order_status DEFAULT 'pending',

-- Delivery Logistics
delivery_agent_name TEXT, delivery_agent_phone TEXT,

-- Exception Handling
cancellation_reason TEXT,
cancelled_by UUID REFERENCES public.profiles (id), -- Changed from BIGINT to UUID
customer_alert_message TEXT,

-- Modification Tracking
modification_pending BOOLEAN DEFAULT FALSE,
modification_request JSONB,

-- Timestamps
created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    accepted_at TIMESTAMP WITH TIME ZONE,
    in_kitchen_at TIMESTAMP WITH TIME ZONE,
    out_for_delivery_at TIMESTAMP WITH TIME ZONE,
    done_at TIMESTAMP WITH TIME ZONE,
    cancelled_at TIMESTAMP WITH TIME ZONE
);

-- 8. INDEXES (Performance)
CREATE INDEX idx_orders_branch_id ON public.orders (branch_id);

CREATE INDEX idx_orders_status ON public.orders (status);

CREATE INDEX idx_orders_created_at ON public.orders (created_at);

CREATE INDEX idx_customers_phone ON public.customers (phone_number);

CREATE INDEX idx_profiles_user_id ON public.profiles (id);

-- 9. REALTIME ENABLEMENT
ALTER PUBLICATION supabase_realtime ADD TABLE public.orders;

-- 10. ROW LEVEL SECURITY (RLS)
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.branches ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.customers ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.customer_addresses ENABLE ROW LEVEL SECURITY;

-- Basic Policies (Open for Managers)
CREATE POLICY "Public view branches" ON public.branches FOR
SELECT TO authenticated USING (true);

CREATE POLICY "Auth users view profiles" ON public.profiles FOR
SELECT TO authenticated USING (true);

CREATE POLICY "Auth users view orders" ON public.orders FOR
SELECT TO authenticated USING (true);

CREATE POLICY "Auth users update orders" ON public.orders
FOR UPDATE
    TO authenticated USING (true);

CREATE POLICY "Auth users insert orders" ON public.orders FOR INSERT TO authenticated
WITH
    CHECK (true);

CREATE POLICY "Auth users manage customers" ON public.customers FOR ALL TO authenticated USING (true);

CREATE POLICY "Auth users manage addresses" ON public.customer_addresses FOR ALL TO authenticated USING (true);

-- 11. AUTOMATION: New Auth User -> Create Profile
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger AS $$
BEGIN
  INSERT INTO public.profiles (id, full_name, role)
  VALUES (
    new.id, 
    COALESCE(new.raw_user_meta_data->>'full_name', 'New Manager'),
    'branch_manager'
  );
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

-- 12. AUTOMATION: Daily Sequence ID
CREATE OR REPLACE FUNCTION set_daily_id()
RETURNS TRIGGER AS $$
BEGIN
  NEW.daily_seq := (
    SELECT COALESCE(MAX(daily_seq), 0) + 1
    FROM public.orders
    WHERE DATE(created_at) = DATE(NEW.created_at)
  );
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_set_daily_id
BEFORE INSERT ON public.orders
FOR EACH ROW
EXECUTE FUNCTION set_daily_id();

-- 13. SEED DATA (Optional Branch to Start)
INSERT INTO
    public.branches (name, phone_contact, zones)
VALUES (
        'Main Branch',
        '01012345678',
        '[]'
    );

-- =============================================
-- 14. ADMIN PERMISSIONS (CRITICAL FIXES)
-- =============================================

-- Allow Admins/Managers to ADD new branches
CREATE POLICY "Enable insert for authenticated users" ON "public"."branches" AS PERMISSIVE FOR INSERT TO authenticated
WITH
    CHECK (true);

-- Allow Admins/Managers to EDIT branches
CREATE POLICY "Enable update for authenticated users" ON "public"."branches" AS PERMISSIVE
FOR UPDATE
    TO authenticated USING (true)
WITH
    CHECK (true);

-- Allow Admins/Managers to DELETE branches
CREATE POLICY "Enable delete for authenticated users" ON "public"."branches" AS PERMISSIVE FOR DELETE TO authenticated USING (true);

-- Function to get comprehensive customer context by phone number
create or replace function get_customer_context(phone_input text)
returns json
language plpgsql
security definer -- Runs with admin privileges to read data
as $$
declare
    cust_record record;
    addr_list json;
    active_ord json;
    result json;
begin
    -- 1. Get Customer Details
    select * into cust_record from customers where phone_number = phone_input;

    -- If customer does not exist, return a specific structure
    if not found then
        return json_build_object(
            'found', false,
            'message', 'User not found'
        );
    end if;

    -- 2. Get All Addresses for this customer
    select coalesce(json_agg(t), '[]'::json) into addr_list
    from (
        select * from customer_addresses 
        where customer_id = cust_record.id
        order by is_default desc, created_at desc
    ) t;

    -- 3. Get the ONE Current Active Order (Newest first, excluding done/cancelled)
    select row_to_json(t) into active_ord
    from (
        select * from orders
        where customer_id = cust_record.id
        and status not in ('done', 'cancelled')
        order by created_at desc
        limit 1
    ) t;

    -- 4. Build the Final JSON Response
    result := json_build_object(
        'found', true,
        'customer', row_to_json(cust_record),
        'addresses', addr_list,
        'active_order', active_ord 
    );

    return result;
end;
$$;

-- Migration: Add cancellation_dismissed column to orders table
-- Purpose: Track when cancelled order notifications have been dismissed by managers
-- This replaces the localStorage-based approach with a database solution
ALTER TABLE public.orders
ADD COLUMN IF NOT EXISTS cancellation_dismissed BOOLEAN DEFAULT FALSE;
-- Add index for performance when filtering dismissed cancellations
CREATE INDEX IF NOT EXISTS idx_orders_cancellation_dismissed ON public.orders (cancellation_dismissed)
WHERE
    status = 'cancelled';
-- Comment for documentation
COMMENT ON COLUMN public.orders.cancellation_dismissed IS 'Tracks if managers have dismissed the cancellation notification for this order';

-- =============================================
-- PHASE 1: MENU & CMS SCHEMA EXPANSION
-- =============================================

-- 1. SITE SETTINGS (For the "White Label" features)
-- This stores the logo, colors, and slogans so you can edit them from the Admin Panel.
CREATE TABLE IF NOT EXISTS public.site_settings (
    key TEXT PRIMARY KEY, -- e.g. 'brand_name', 'primary_color'
    value TEXT, -- e.g. 'Tawriqa', '#415A3E'
    type TEXT DEFAULT 'text', -- 'text', 'image', 'color', 'boolean'
    description TEXT, -- To help the admin know what this does
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone ('utc'::text, now())
);

-- Enable RLS
ALTER TABLE public.site_settings ENABLE ROW LEVEL SECURITY;
-- Allow everyone to READ settings (so the website knows what color to use)
CREATE POLICY "Public read settings" ON public.site_settings FOR
SELECT USING (true);
-- Allow only Managers/Admins to UPDATE settings
CREATE POLICY "Admins update settings" ON public.site_settings
FOR UPDATE
    TO authenticated USING (true);
-- Allow only Managers/Admins to INSERT new settings
CREATE POLICY "Admins insert settings" ON public.site_settings FOR INSERT TO authenticated
WITH
    CHECK (true);
-- Allow only Managers/Admins to DELETE settings
CREATE POLICY "Admins delete settings" ON public.site_settings FOR DELETE TO authenticated USING (true);

-- 2. MENU CATEGORIES (e.g. "Sweet Feteer", "Drinks")
CREATE TABLE IF NOT EXISTS public.menu_categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name_ar TEXT NOT NULL,
    name_en TEXT,
    image_url TEXT,
    sort_order INTEGER DEFAULT 0, -- To control which comes first
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone ('utc'::text, now())
);

ALTER TABLE public.menu_categories ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public read categories" ON public.menu_categories FOR
SELECT USING (true);

CREATE POLICY "Admins manage categories" ON public.menu_categories FOR ALL TO authenticated USING (true);

-- 3. MENU ITEMS (The actual food)

CREATE TABLE IF NOT EXISTS public.menu_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id BIGINT REFERENCES public.menu_categories (id) ON DELETE SET NULL,
    name_ar TEXT NOT NULL,
    name_en TEXT,
    description_ar TEXT,
    description_en TEXT,
    base_price DECIMAL(10, 2) NOT NULL, -- The default price
    image_url TEXT,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone ('utc'::text, now())
);

ALTER TABLE public.menu_items ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public read items" ON public.menu_items FOR
SELECT USING (true);

CREATE POLICY "Admins manage items" ON public.menu_items FOR ALL TO authenticated USING (true);

-- 4. BRANCH SPECIFIC PRICES (The "Tawriqa" Requirement)
-- If a row exists here, we use THIS price. If not, we use base_price.
CREATE TABLE IF NOT EXISTS public.branch_item_prices (
    branch_id BIGINT REFERENCES public.branches (id) ON DELETE CASCADE,
    item_id BIGINT REFERENCES public.menu_items (id) ON DELETE CASCADE,
    price DECIMAL(10, 2) NOT NULL,
    is_available BOOLEAN DEFAULT TRUE, -- Can hide an item just for this branch
    choice_prices JSONB DEFAULT '{}', -- Store item-specific prices for choices: { "choice_id": price }
    PRIMARY KEY (branch_id, item_id)
);

ALTER TABLE public.branch_item_prices ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public read branch prices" ON public.branch_item_prices FOR
SELECT USING (true);

CREATE POLICY "Admins manage branch prices" ON public.branch_item_prices FOR ALL TO authenticated USING (true);

-- 5. INSERT DEFAULT SETTINGS (To start off)
INSERT INTO public.site_settings (key, value, type, description) VALUES
('brand_name_ar', 'توريقة', 'text', 'Restaurant Name in Arabic'),
('brand_name_en', 'Tawriqa', 'text', 'Restaurant Name in English'),
('primary_color', '#415A3E', 'color', 'Main Theme Color (Buttons/Links)'),
('secondary_color', '#CCA876', 'color', 'Accent Color (Stars/Highlights)'),
('hero_title_ar', 'بين الطبقات.. حكايات', 'text', 'Main Headline on Website'),
('hero_image_url', '', 'image', 'Main background image URL')
ON CONFLICT (key) DO NOTHING;

-- =============================================
-- PHASE 1 (Part 2): OPTIONS & MODIFIERS
-- =============================================

-- 1. OPTION GROUPS (e.g. "Size", "Spiciness", "Add-ons")
CREATE TABLE IF NOT EXISTS public.option_groups (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name_ar TEXT NOT NULL,       -- e.g. "الحجم"
    name_en TEXT,                -- e.g. "Size"

-- Control Logic


min_selection INTEGER DEFAULT 0, -- 0 = Optional, 1 = Required
    max_selection INTEGER DEFAULT 1, -- 1 = Single Choice (Radio), >1 = Multiple (Checkbox)
    
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

ALTER TABLE public.option_groups ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public read option groups" ON public.option_groups FOR
SELECT USING (true);

CREATE POLICY "Admins manage option groups" ON public.option_groups FOR ALL TO authenticated USING (true);

-- 2. OPTION CHOICES (e.g. "Small", "Large", "Spicy")
CREATE TABLE IF NOT EXISTS public.option_choices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id BIGINT REFERENCES public.option_groups (id) ON DELETE CASCADE,
    name_ar TEXT NOT NULL, -- e.g. "كبير"
    name_en TEXT, -- e.g. "Large"
    price_modifier DECIMAL(10, 2) DEFAULT 0.00, -- e.g. 20.00 (Adds 20 EGP)
    is_available BOOLEAN DEFAULT TRUE
);

ALTER TABLE public.option_choices ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public read option choices" ON public.option_choices FOR
SELECT USING (true);

CREATE POLICY "Admins manage option choices" ON public.option_choices FOR ALL TO authenticated USING (true);

-- 3. LINK ITEMS TO GROUPS (The Bridge)
-- This allows you to reuse the "Size" group for 10 different pizzas without creating it 10 times.
CREATE TABLE IF NOT EXISTS public.item_option_links (
    item_id BIGINT REFERENCES public.menu_items (id) ON DELETE CASCADE,
    group_id BIGINT REFERENCES public.option_groups (id) ON DELETE CASCADE,
    sort_order INTEGER DEFAULT 0, -- Which question appears first?
    PRIMARY KEY (item_id, group_id)
);

ALTER TABLE public.item_option_links ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public read links" ON public.item_option_links FOR
SELECT USING (true);

CREATE POLICY "Admins manage links" ON public.item_option_links FOR ALL TO authenticated USING (true);

-- Add 3rd Language columns to Categories
ALTER TABLE public.menu_categories
ADD COLUMN IF NOT EXISTS name_other TEXT;

-- Add 3rd Language columns to Items
ALTER TABLE public.menu_items
ADD COLUMN IF NOT EXISTS name_other TEXT,
ADD COLUMN IF NOT EXISTS description_other TEXT;

-- Add 3rd Language columns to Options
ALTER TABLE public.option_groups
ADD COLUMN IF NOT EXISTS name_other TEXT;

ALTER TABLE public.option_choices
ADD COLUMN IF NOT EXISTS name_other TEXT;

-- 1. Create a public bucket named 'menu_images'
INSERT INTO
    storage.buckets (id, name, public)
VALUES (
        'menu_images',
        'menu_images',
        true
    )
ON CONFLICT (id) DO NOTHING;

-- 2. Allow anyone to VIEW images (Public)
CREATE POLICY "Public Access" ON storage.objects FOR
SELECT USING (bucket_id = 'menu_images');

-- 3. Allow Authenticated Users (Admins) to UPLOAD images
CREATE POLICY "Admin Upload" ON storage.objects FOR INSERT TO authenticated
WITH
    CHECK (bucket_id = 'menu_images');

-- 4. Allow Admins to UPDATE/DELETE
CREATE POLICY "Admin Update" ON storage.objects
FOR UPDATE
    TO authenticated USING (bucket_id = 'menu_images');

CREATE POLICY "Admin Delete" ON storage.objects FOR DELETE TO authenticated USING (bucket_id = 'menu_images');

-- DELETE OLD SETTINGS TO RESET (Safe for dev)
DELETE FROM public.site_settings;

-- INSERT ALL CONFIGURABLE KEYS
INSERT INTO public.site_settings (key, value, type, description) VALUES
-- Branding
('brand_name_ar', 'توريقة', 'text', 'اسم المطعم (عربي)'),
('brand_name_en', 'Tawriqa', 'text', 'Restaurant Name (English)'),
('brand_name_other', 'Таврика', 'text', 'Restaurant Name (Russian)'), -- RU
('primary_color', '#415A3E', 'color', 'Main Theme Color'),
('logo_url', '', 'image', 'Website Logo'),

-- Hero Section (Main Page)
('hero_title_ar', 'بين الطبقات.. حكايات', 'text', 'Hero Title (Arabic)'),
('hero_title_en', 'Stories between layers...', 'text', 'Hero Title (English)'),
('hero_title_other', 'Истории между слоями...', 'text', 'Hero Title (Russian)'),

('hero_subtitle_ar', 'طعم أصيل بلمسة عصرية', 'text', 'Hero Subtitle (Arabic)'),
('hero_subtitle_en', 'Authentic taste, modern touch', 'text', 'Hero Subtitle (English)'),
('hero_subtitle_other', 'Аутентичный вкус', 'text', 'Hero Subtitle (Russian)'),

('hero_image_url', '', 'image', 'Main Background Image'),

-- Contacts
('phone_number', '+201xxxxxxxxx', 'text', 'Hotline'),
('whatsapp_number', '+201xxxxxxxxx', 'text', 'WhatsApp Number (for link)'),
('facebook_link', '', 'text', 'Facebook URL'),
('instagram_link', '', 'text', 'Instagram URL')
ON CONFLICT (key) DO NOTHING;

INSERT INTO
    public.site_settings (key, value, type, description)
VALUES (
        'supported_languages',
        '["ar", "en", "ru"]',
        'json',
        'List of active languages on website'
    ),
    (
        'default_language',
        'ar',
        'text',
        'Default language when site loads'
    )
ON CONFLICT (key) DO NOTHING;

ALTER TABLE public.option_groups
ADD COLUMN IF NOT EXISTS is_price_replacement BOOLEAN DEFAULT FALSE;
-- When TRUE: choice.price_modifier IS the selling price (ignores base_price)
-- When FALSE: choice.price_modifier is ADDED to base_price (e.g., +5 for extra sauce)

ALTER TABLE public.menu_items
ADD COLUMN IF NOT EXISTS variations JSONB DEFAULT '{"sizes": [], "extras": []}';

ALTER TABLE public.item_option_links
ADD COLUMN IF NOT EXISTS choice_prices JSONB DEFAULT '{}';
-- Format: { "choice_id": price, "choice_id": price, ... }
-- Example: { "1": 35, "2": 50, "3": 70, "4": 0 }

ALTER TABLE public.branch_item_prices
ADD COLUMN IF NOT EXISTS choice_prices JSONB DEFAULT '{}';
-- Ensures existing tables get the column too

-- =============================================
-- PHASE 2: COMPREHENSIVE SITE SETTINGS
-- =============================================

INSERT INTO
    public.site_settings (key, value, type, description)
VALUES
    -- Social Media (extended)
    (
        'tiktok_link',
        '',
        'text',
        'TikTok URL'
    ),
    (
        'twitter_link',
        '',
        'text',
        'Twitter/X URL'
    ),

-- SEO Meta Tags
(
    'meta_description_ar',
    'توريقة - أشهى الفطائر المصرية الأصيلة',
    'text',
    'SEO Meta Description (Arabic)'
),
(
    'meta_description_en',
    'Tawriqa - Authentic Egyptian pastries',
    'text',
    'SEO Meta Description (English)'
),
(
    'meta_keywords_ar',
    'فطير، توريقة، مصري، توصيل',
    'text',
    'SEO Keywords (Arabic)'
),
(
    'meta_keywords_en',
    'feteer, egyptian, pastry, delivery',
    'text',
    'SEO Keywords (English)'
),
(
    'og_image_url',
    '',
    'image',
    'Open Graph/Social Share Image'
),
(
    'favicon_url',
    '',
    'image',
    'Browser Favicon'
),

-- Page Titles
(
    'page_title_home_ar',
    'الرئيسية',
    'text',
    'Home page title (Arabic)'
),
(
    'page_title_menu_ar',
    'المنيو',
    'text',
    'Menu page title (Arabic)'
),
(
    'page_title_checkout_ar',
    'إتمام الطلب',
    'text',
    'Checkout page title (Arabic)'
),
(
    'page_title_location_ar',
    'اختيار الموقع',
    'text',
    'Location page title (Arabic)'
),
(
    'page_title_home_en',
    'Home',
    'text',
    'Home page title (English)'
),
(
    'page_title_menu_en',
    'Menu',
    'text',
    'Menu page title (English)'
),
(
    'page_title_checkout_en',
    'Checkout',
    'text',
    'Checkout page title (English)'
),
(
    'page_title_location_en',
    'Location',
    'text',
    'Location page title (English)'
),

-- Business Info
(
    'address_ar',
    '',
    'text',
    'Business Address (Arabic)'
),
(
    'address_en',
    '',
    'text',
    'Business Address (English)'
),
(
    'working_hours_ar',
    'يومياً من 10 صباحاً - 12 منتصف الليل',
    'text',
    'Working Hours (Arabic)'
),
(
    'working_hours_en',
    'Daily 10 AM - 12 AM',
    'text',
    'Working Hours (English)'
),
(
    'email',
    '',
    'text',
    'Contact Email'
),
(
    'google_maps_link',
    '',
    'text',
    'Google Maps URL'
),

-- Footer
(
    'footer_tagline_ar',
    'بين الطبقات.. حكايات',
    'text',
    'Footer Tagline (Arabic)'
),
(
    'footer_tagline_en',
    'Stories between layers...',
    'text',
    'Footer Tagline (English)'
),
(
    'footer_copyright_ar',
    '© 2026 توريقة - جميع الحقوق محفوظة',
    'text',
    'Copyright Text (Arabic)'
),
(
    'footer_copyright_en',
    '© 2026 Tawriqa. All rights reserved.',
    'text',
    'Copyright Text (English)'
),

-- Legal Pages
(
    'terms_url',
    '',
    'text',
    'Terms & Conditions URL'
),
(
    'privacy_url',
    '',
    'text',
    'Privacy Policy URL'
),
(
    'about_url',
    '',
    'text',
    'About Us URL'
),

-- Theme extras
(
    'menu_cover',
    '',
    'image',
    'Menu Page Cover Image'
)
ON CONFLICT (key) DO NOTHING;

-- =============================================
-- PHASE 3: BRANCHES ENHANCEMENT FOR LANDING PAGE
-- =============================================

-- Add multilingual names and addresses to branches
ALTER TABLE public.branches
ADD COLUMN IF NOT EXISTS name_ar TEXT,
ADD COLUMN IF NOT EXISTS name_en TEXT,
ADD COLUMN IF NOT EXISTS address_ar TEXT,
ADD COLUMN IF NOT EXISTS address_en TEXT,
ADD COLUMN IF NOT EXISTS google_maps_embed TEXT,
ADD COLUMN IF NOT EXISTS google_maps_link TEXT;

-- =============================================
-- PHASE 4: ABOUT PAGE CONTENT & GALLERY
-- =============================================

INSERT INTO
    public.site_settings (key, value, type, description)
VALUES
    -- About Page Hero
    (
        'about_hero_image',
        '',
        'image',
        'About page hero image'
    ),

-- Story Section
(
    'about_story_title_ar',
    'القصة وما فيها..',
    'text',
    'Story title (Arabic)'
),
(
    'about_story_title_en',
    'The Story...',
    'text',
    'Story title (English)'
),
(
    'about_story_title_other',
    'Наша история...',
    'text',
    'Story title (Russian)'
),
(
    'about_story_text_ar',
    'بدأنا من شغف بسيط بالفطير المصري الأصيل',
    'text',
    'Story text (Arabic)'
),
(
    'about_story_text_en',
    'We started with a passion for authentic Egyptian Feteer',
    'text',
    'Story text (English)'
),
(
    'about_story_text_other',
    'Мы начали со страсти к аутентичному фетиру',
    'text',
    'Story text (Russian)'
),
(
    'about_story_image',
    '',
    'image',
    'Story section image'
),

-- Vision Section
(
    'about_vision_title_ar',
    'رؤيتنا',
    'text',
    'Vision title (Arabic)'
),
(
    'about_vision_title_en',
    'Our Vision',
    'text',
    'Vision title (English)'
),
(
    'about_vision_title_other',
    'Наше видение',
    'text',
    'Vision title (Russian)'
),
(
    'about_vision_text_ar',
    'نطمح إننا نكون الوجهة الأولى لعشاق الفطير المصري',
    'text',
    'Vision text (Arabic)'
),
(
    'about_vision_text_en',
    'We aspire to be the first destination for Feteer lovers',
    'text',
    'Vision text (English)'
),
(
    'about_vision_text_other',
    'Мы стремимся стать первым местом для любителей фетира',
    'text',
    'Vision text (Russian)'
),
(
    'about_vision_image',
    '',
    'image',
    'Vision section image'
),

-- Values Section
(
    'about_values_title_ar',
    'قيمنا',
    'text',
    'Values title (Arabic)'
),
(
    'about_values_title_en',
    'Our Values',
    'text',
    'Values title (English)'
),
(
    'about_values_title_other',
    'Наши ценности',
    'text',
    'Values title (Russian)'
),
(
    'about_values_text_ar',
    'في توريقة، القيم مش مجرد كلمات مكتوبة',
    'text',
    'Values text (Arabic)'
),
(
    'about_values_text_en',
    'At Tawriqa, values are the spirit we live by',
    'text',
    'Values text (English)'
),
(
    'about_values_text_other',
    'В Тавриге ценности - это дух, которым мы живем',
    'text',
    'Values text (Russian)'
),
(
    'about_values_image',
    '',
    'image',
    'Values section image'
),

-- Products Section
(
    'about_products_title_ar',
    'منتجاتنا',
    'text',
    'Products title (Arabic)'
),
(
    'about_products_title_en',
    'Our Products',
    'text',
    'Products title (English)'
),
(
    'about_products_title_other',
    'Наши продукты',
    'text',
    'Products title (Russian)'
)
ON CONFLICT (key) DO NOTHING;

-- Gallery table for About page product images
CREATE TABLE IF NOT EXISTS public.about_gallery (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    image_url TEXT NOT NULL,
    alt_text TEXT,
    sort_order INTEGER DEFAULT 0,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone ('utc'::text, now())
);

ALTER TABLE public.about_gallery ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public read gallery" ON public.about_gallery FOR
SELECT USING (true);

CREATE POLICY "Admins manage gallery" ON public.about_gallery FOR ALL TO authenticated USING (true);

-- =============================================
-- PHASE 5: WEBSITE CHECKOUT SUPPORT
-- =============================================
-- Add columns for guest checkout (website without WhatsApp registration)

ALTER TABLE public.orders
ADD COLUMN IF NOT EXISTS customer_name TEXT,
ADD COLUMN IF NOT EXISTS customer_phone TEXT,
ADD COLUMN IF NOT EXISTS customer_address TEXT,
ADD COLUMN IF NOT EXISTS delivery_lat FLOAT,
ADD COLUMN IF NOT EXISTS delivery_lng FLOAT,
ADD COLUMN IF NOT EXISTS service_type TEXT DEFAULT 'pickup',
ADD COLUMN IF NOT EXISTS total DECIMAL(10, 2) DEFAULT 0.00;

-- Add comment for documentation
COMMENT ON COLUMN public.orders.customer_name IS 'Guest checkout customer name (website orders)';

COMMENT ON COLUMN public.orders.customer_phone IS 'Guest checkout customer phone (website orders)';

COMMENT ON COLUMN public.orders.customer_address IS 'Guest checkout delivery address text (website orders)';

COMMENT ON COLUMN public.orders.service_type IS 'pickup or delivery';

-- Allow public INSERT for guest checkout
CREATE POLICY "Public insert orders" ON public.orders FOR INSERT
WITH
    CHECK (true);

-- Payment method settings for admin control
INSERT INTO public.site_settings (key, value, type, description) VALUES
('payment_cash_enabled', 'true', 'boolean', 'Enable cash on delivery'),
('payment_card_enabled', 'false', 'boolean', 'Enable card payments via Paymob'),
('paymob_iframe_id', '', 'text', 'Paymob Iframe ID from dashboard'),
('paymob_integration_id', '', 'text', 'Paymob Integration ID from dashboard')
ON CONFLICT (key) DO NOTHING;

-- Add is_delivery_available column to branches table
ALTER TABLE public.branches
ADD COLUMN IF NOT EXISTS is_delivery_available BOOLEAN DEFAULT TRUE;

-- Comment
COMMENT ON COLUMN public.branches.is_delivery_available IS 'If false, delivery service is suspended for this branch (Pickup only)';

ALTER TABLE public.branches
ADD COLUMN IF NOT EXISTS name_ru TEXT,
ADD COLUMN IF NOT EXISTS address_ru TEXT;